---
layout: post
title: Data mining the Internet (for solutions)
---

I woke up to over 120 messages in the Slack "help" channel we have set up for the class, all about [this tutorial](http://programminghistorian.org/lessons/data-mining-the-internet-archive). I'm braced. I'm ready. I've got a whole pot of tea and I'm prepared to do a lot of command+F and Googling. #letsdothis

oh. right. I have a mac. 

The wild and erratic struggle everyone else seems to be having has been sidestepped for me this time. yay?! 

and I did it. I spoke too soon. #jinxedit

**The Problems**

Despite not having the issues that were coming up for those students working on Windows machines, I ran into a few problems getting access to internetarchive through the command line, and then had more issues trying to figure out what I was doing the Python and the scripts we were writing. Not understanding the language we were coding in meant that what stuck out as glaring syntax errors to more experienced digital gurus looked just fine to me. I think the biggest takeaway from this tutorial (besides the cool stuff you can do in the 'back channels' of the internet to download lots of primary sources, was that if I do want to continue working in the digital field that I need to focus on learning and understanding the basics of the languages and systems we use. While having tutorials like these walk you through the steps is amazing, and makes learning more interesting, being able to figure out some steps on your own would be so beneficial later on down the road. 

*Problem the First*

When I input: 

```import internetarchive
search = internetarchive.search_items('collection:bplscas')
print search.num_found
```

it resulted in... nada. syntax error. import error. all kinda errors. The good old fashioned "restart and try again" worked, which was great. I don't really know why that works. I guess its because the computer has a chance to get it's shit together and start with everything all set and ready rather than patched together? 

Most of my issues were syntax errors on my part (sloppy frustrated typing) and also issues around not really knowing and understanding python. It wasn't until we were in class and Shawn mentioned that python reads 4 spaces and a tab as different things that I realized what was wrong. Because I was doing a mix and match of typing in and copy-pasting bits of code, both of these "meaningful blanks" were showing up, which was confusing the python shell. 

![error screenshot](/images/Screen.Shot.2016-01-31.at.6.46.37.PM.png)

Once this got figured out, and I was consistently using indent rather than 4 spaces in all of the script I was tying and making sure any that I copy-pasted matched, things started running smoothly again. For a while. 

*Problem the Second* 

Running the 'for loop' in the python shell to 'print' out the identifiers of the internetarchive letters resulted in a big ol nothing, and I have no idea why. No error message. No "sorry I can't do that Dave". Nothing. At this point I was frustrated, so I washed my dishes. Which I was definitley not going to do tonight, so thanks digital history, for helping me be productive around the house. 

And now it works. I didn't even restart. or quit anything. It just decided to actually run the script this time. Yay?

Right, well... lets just move on and see what happens when we run the next script. 

oh. my. actual. god. 

I don't know why it isn't working. It is the exact code they wrote. What am i doing wrong? I've double checked everything. I'm being careful with inputs and I made sure there wasn't any extra (or missing) white space because I know python cares about that. (N.B. I'm editing some notes I wrote while working through the tutorial, it is now a few weeks later, and now I know what I did wrong, but I felt this angst was important to keep in my published notes) 

I have: 

```#!/usr/bin/python

import os
import pymarc

path = '/path/to/dir/with/xmlfiles/'

def get_place_of_pub(record):
    try:
        place_of_pub = record['260']['a']
        print place_of_pub
    except Exception as e:
        print e

for file in os.listdir(path):
    if file.endswith('.xml'):
        pymarc.map_xml(get_place_of_pub, path + file)
```

saved as script1.py and run by the command `python script1.py` while in the correct directory.

Then I did a bit of editing, thinking I could finally make this damn pymarc thing work.

Big ol' case of the nopes. And I still don't know why. I am following the instructions exactly. What am I doing wrong? (you see what is wrong, intrepid reader, since I hinted soooo heavily at the beginning of my entry what was wrong). Oh look! `path = '/path/to/dir/with/xmlfiles/'` Now THAT doesn't look right, does it? Well, it did to me so don't be so judgemental, intrepid reader. One of the steps that the tutorial skips is reminding you that while this script is the framework that will work for everyone, there are aspects that are unique to each individual running the command. So insert the proper path, and we're good to go! 

*Problem the Third*

Really the big problem is that none of the coffee I'm drinking is strong enough. THAT'S what it is. I swear. 

![python error screenshot](/images/Screen.Shot.2016-01-31.at.6.46.37.PM.png)

Okay so my script is correct, and something is still going wrong. Alright. Lets google some shit. (rolls up sleeves)

I input `AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'` into the magic internet machine, and a bunch of smart programmer people chimed in on various chat pages with potential solutions. I started working through the ones that seemed fairly straightforward and easy, and focused on making minor changes, because I knew that my computer is new, fairly untouched, and has no real problems, so whatever was going wrong would be something relatively minor in comparison to a computer that has been around the block a few times and might have some big issues that have built up over time. 

Easiest solution: `pip install requests six` - nah, it says that requirements are already fulfilled. huh. Now what?

The next suggestion: go to /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python and while in this directory type `$ rm six.py` `six.pyc` into the command line. This solution forces the console to use pip instead of python directory, and should solve the issue. Went back to run the script with hopes high. nope. 

zip. zilch. nada. 

Next solution: Try updating the 'six' library: `'pip install -U six'`.

nah.

We tweeted proghist about it, and I called in the cavalry (my computer programmer brother). 

Eventually we realized that I was working with an outdate version of python. So `sudo pip install --update six` fixed everything. Which is super confusing. Because as you can see above, I already tried installing six. Or at least, I thought I had. I'm unclear why the syntax needed to be this and not what I was given for solution #2, which was on a mac chat room. I know that it needed an update and not an install, but I would think that the -U flag stands for 'update'. So using sudo was necessary (it is becoming increaslingly clear I almost always need to use sudo to run installs through the command line), and the second hyphen in front of the flag was too? 

**Reflection**

Running through solving these errors was almost more educational than the tutorial itself. Problem solving, learning to walk away and let the computer figure itself out, learning what sorts of solutions will or will not work on my particular machine, and discovering that I have to read through and *understand* scripts if I want them to run properly and give me the results that I am looking for. 

Oh, also, by the way, I downloaded some files from Internet Archive and analyzed some of their indentifiers and some other cool stuff, including error tracking, and scraping specific information ABOUT the files. Nifty. 
